### ISSUE TITLE
[BUG] 1.18 mobs dont get removed and custom items are not droped when they are

### ISSUE THREAD

**Issue by soupcoup** [MythicDrops/MythicDrops#621]
mobs not droping items or being removed 1.18

## Description
custom mobs when dieing in 1.18 dont drop any items and sometimes remain on the ground and i get a console error

## Expected Behavior
Mob Should die and drop custom drop

## Actual Behavior
Console Error and mob is not removed and remains dead on the ground 
https://pastebin.com/ZmgjQrQd

## Possible Fix
no clue

## Steps to Reproduce

1. update mythic mobs on my server
2. kill a mob
3. mob remains
4. console error

## Context
It has stoped my server players from getting the essential item that allows them to get custom items and such

## Your Environment
![2021-12-08_21 47 07](https://user-images.githubusercontent.com/69484390/145331100-f78edadc-f8ac-402b-beb8-707b4fe11006.png)
rsion used (`/version MythicDrops`):1.13.1
* Environment name and version (`/version`): 1.18 minecraft

**Comment by UltraFaceguy** [comment]
I have several questions regarding this... Also I don't think a bug label is the right choice, since MythicDrops has not been released for 1.18 yet. Anwyays:

- Where... does that version command come from? /version MythicDrops ? MythicDrops for 1.17 (latest) is on 8.0.1
- I don't see MythicDrops in your plugin list. Were there errors on startup? If it's not installed, how did version return anything?
- Step 1 in the reproduction steps seems odd, because this is not MytrhicMobs, but MythicDrops, a different plugin. You sure you're in the right place?

**Comment by ToppleTheNun** [comment]
This is a MythicMobs issue, not a MythicDrops issue.

**Comment by soupcoup** [comment]
wrong forum idk how i got here sorry
