### ISSUE TITLE
Socket gem basic material can be renamed in anvil and work as a socket [BUG]

### ISSUE THREAD

**Issue by zorkenlide** [MythicDrops/MythicDrops#631]
## Actual Behavior
My socket gem material ID is Quartz. Players can make their own fake socket gems by putting normal quartz into the anvil and renaming it to the exact name (Needles I) for example. Then they can put it into armor and the armor gets all the right properties of the real socket.

Do you know about this bug? Is there any way to prevent this? I use "prevent-crafting-with-gems: true" but that only works for renaming true socket gems, not the material ID item.

Possible workaround would be using a base item which players cant get in the survival, but I am trying to find a different solution first.

Cheers!

**Comment by DoubleYouCash** [comment]
Any chance that this can be revisited? It's been over a year and I am now dealing with this same issue on my server. 

@zorkenlide Were you ever able to find a good workaround for this? I was also thinking of using an unobtainable item for my sockets but that seems like a sub-par solution.

Thanks!

**Comment by ToppleTheNun** [comment]
This isn't an issue if you're on the latest version of MythicDrops, running Minecraft 1.16+, and have `disable-legacy-item-checks` set to `true`. The issue comes when `disable-legacy-item-checks` is set to `true` and we need to check against item name instead of persistent data stored on the item itself.

If we're only using the persistent data (non-legacy) check, then we can ignore the names of the items and just check the data to see if the item is a socket gem.

There isn't really a good way to prevent this from happening without disabling the legacy check, as colors in the socket gems can change and the format of the socket gem name can change (and it can clearly be abused).

**Comment by DoubleYouCash** [comment]
Yes, I was just coming back to here after seeing that there was a newer version than the one that I had. I assumed that since there was an issue here still not closed that it was still an issue in the latest version, but after some experimentation with the new version, it is not an issue. Thank you!
